---
output:
  pdf_document:
    number_sections: true
    latex_engine: xelatex
    pandoc_args: [
      "-V", "linkcolor=blue",
      "-V", "citecolor=blue",
      "-V", "urlcolor=blue"
    ]
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman}
  - \usepackage{multicol}
  - \usepackage{ragged2e}
  - \usepackage{amsmath}
---

\title{\textbf{STOR 390: HOMEWORK 8}}
\author{\textbf{Riley Harper}}
\date{\textbf{\today}}
\maketitle


\renewcommand\abstractname{}
\renewcommand{\refname}{References in the Discussion}
\begin{abstract}
\textbf{Abstract:} This homework explores various aspects of data privacy and fairness in statistical analysis, integrating topics such as differential privacy and the ethical responsibilities surrounding data interpretation. By exploring the Randomized Response technique, we demonstrate its effectiveness in maintaining $\varepsilon$-differential privacy and protecting individual responses in sensitive surveys, where $\varepsilon = \ln(3)$. Additionally, we engage with regression models to control for confounding variables such as age and smoking status, illustrating how these factors can influence the outcomes in studies related to lung capacity.
\end{abstract}
\vspace{1em}
\begin{multicols}{2}

\section*{Question 1}
Prove that Randomized Response Differential Privacy is $\varepsilon-$differentially private. In particular, show that $\varepsilon = ln(3)$.  

The Randomized Response technique is a method used to protect the privacy of individuals in surveys, particularly for sensitive questions. The method involves the following steps,
\begin{enumerate}
    \item The respondent flips a fair coin.
    \item If the coin lands heads, they flip another coin,
    \begin{itemize}
        \item If the second coin lands heads, they answer ``Yes''.
        \item If the second coin lands tails, they answer ``No''.
    \end{itemize}
    \item If the coin lands tails, they answer truthfully.
\end{enumerate}

Let $f$ denote the true answer, where $f=1$ for ``Yes'' and $f=0$ for ``No''. The probability of responding  ``Yes'' ($Y=1$) is calculated as follows,
$$P[Y=1 \mid f=1] = \frac{1}{2} \cdot 1 + \frac{1}{2} \cdot \frac{1}{2} = \frac{3}{4}$$
$$P[Y=1 \mid f=0] = \frac{1}{2} \cdot 0 + \frac{1}{2} \cdot \frac{1}{2} = \frac{1}{4}$$

The definition of $\varepsilon$-differential privacy is given by,
$$\varepsilon := \ln\left(\frac{P[Y = y \mid f = 1]}{P[Y = y \mid f = 0]}\right)$$

If we let $y = 1$,
$$\varepsilon = \ln\left(\frac{P[Y = 1 \mid f = 1]}{P[Y = 1 \mid f = 0]}\right) = \ln\left(\frac{\frac{3}{4}}{\frac{1}{4}}\right) = \ln\left(3\right)$$

Therefore, the Randomized Response technique is $\varepsilon$-differentially private with $\varepsilon = \ln(3)$.

\section*{Question 2}
Recall the example of \textit{regressing out} a confounding variable we used in class.  Here, we established that not only is `age` related to lung capacity, but so too is `smoke`.  Interpret the model coefficients produced below, and in particular explain why including both `age` and `smoke` helps to control for confounding.  (\textit{Hint: This should involve interpreting your coefficients \textbf{marginally}.})

```{r, echo=FALSE, fig.cap="Analysis of FEV data by age and smoking status", out.width='\\linewidth', fig.align='center', results='asis'}
library(mplot)
data(fev)

#see if smoking is related to age 
boxplotPlot <- boxplot(age~smoke, ylab = "AGE", xlab = "Smoke 0/1 No/Yes", data = fev)
correlation <- cor(fev$age, fev$fev)
cat("\n\\textbf{Correlation:} ", correlation, "\n")

#regress out your confounder 
mod <- lm(fev~age+smoke, data = fev)
# Generate summary and capture output
summaryOutput <- capture.output(print(summary(mod)))

# wrap text at specified width
wrap_text <- function(text, width) {
  wrapped_lines <- unlist(lapply(text, function(line) {
    strwrap(line, width = width, simplify = FALSE)
  }))
  return(wrapped_lines)
}

# apply text wrapping
wrapped_output <- wrap_text(summaryOutput, 45)  # Adjust width as needed for your column width
cat("\n\\textbf{Model Summary:}")
cat("\\begin{verbatim}")
cat(wrapped_output, sep = "\n")
cat("\\end{verbatim}")
```

\quad Including both `age' and `smoke' is essential for controlling the confounding effects these variables may have on lung capacity (FEV)-forced expiratory volume. Age is a primary determinant of lung capacity. Generally, lung capacity may increase in younger ages, peak, and then decline as part of the natural aging process. By including `age' in our regression, we adjust for these physiological changes with the aim of isolating the impact of other factors like smoking. Also, smoking status has been linked to lung health; smoking can significantly reduce lung capacity. Including this variable helps to quantify its impact on lung capacity while controlling for age differences among subjects. Including both `age' and `smoke' in the model allows us to mitigate the confounding influence one might have on the other. For example, if older individuals in the study are more likely to be smokers, not adjusting for age could lead to overestimating the impact of smoking on lung capacity.

The coefficients from our regression model give us the marginal effects of each variable,
\begin{itemize}
    \item The coefficient of `age' (0.230605) tells us lung capacity is expected to change by 0.230605 units with each additional unit change (in years) of age, holding smoking status constant.
    \item The coefficient of `smoke' (-0.208995) tells us us the lung capacity is expected to change by -0.208995 units with each additional unit change in smoking, holding age constant.
\end{itemize}

\section*{Question 3}
Describe one experimental design technique that could be used to mitigate \textit{known} confounders or batch effects (as opposed to latent batch effects).  

An effective experimental design technique to control for known confounders or batch effects is \textbf{stratified random sampling}. This method can be defined by dividing a population being observed or surveyed into smaller groups, known as strata, that are homogeneous with respect to one or more characteristics which are known to be confounders.

\textbf{Implementation of Stratified Random Sampling (SRS):}

\begin{itemize}
    \item \textbf{Strata Formation:} The first step is to identify the known confounder(s) which might impact the study outcome. The entire population is then divided into subgroups or strata based on these confounders. Each stratum should be homogeneous regarding the confounder (a few examples of confounders could be age, sex, socioeconomic status).
    \item \textbf{Random Sampling:} From each stratum, participants are randomly selected to participate in the study. This ensures that each stratum is represented proportionally or equally, depending on the study design.
    \item \textbf{Control Over Confounding:} By stratifying the population by known confounders, the impact of these confounders is controlled across the treatment groups, reducing their effect on the outcome variable.
\end{itemize}

\quad A few advantages to utilizing SRS include increased precision, improved validity, and efficiency. SRS improves the precision of the study by ensuring that the sample is more representative of the overall population, particularly regarding the confounders that are stratified. SRS also enhances the validity of the results by ensuring that the confounding variables are evenly distributed across all study groups, leading to more reliable and reproducible findings. Finally SRS requires a smaller sample size to achieve the same level of precision compared to simple random sampling, making it more efficient in terms of resources and time. SRS is particularly useful in observational studies and surveys where specific subgroups may have different responses or outcomes. By ensuring these subgroups are adequately represented and controlled for in the study, researchers can make more precise inferences about the effects of the variables being studied.

\section*{Question 4}
I have described our responsibility to proper interpretation as an \textit{obligation} or \textit{duty}.  How might a Kantian Deontologist defend such a claim?  

\quad From the perspective of Kantian Deontology, ethical behavior is grounded in adherence to universal maxims and the fulfillment of duties, irrespective of the consequences. According to Immanuel Kant, actions are morally right when they are performed out of duty and conform to universal law. This approach can be directly applied to the concept of the duty of proper interpretation. According to Kant's principle of universalizability, an act is morally acceptable if it can be universalized, meaning it can consistently be willed as a law that everyone should follow. In terms of proper interpretation, this means that if the act of interpreting information accurately and responsibly could be universalized, it becomes not only a preferable practice but a moral duty. This stems from the desire for a society where truth and understanding are upheld as common values. Kant’s Categorical Imperative demands that we act only according to maxims that could be adopted universally. This imperative implies that misinterpreting or distorting information would be contrary to this principle because it would not be desirable for such practices to become universal law. Thus, a Kantian Deontologist would argue that we have a moral duty to interpret correctly to respect and uphold the rationality and autonomy of all individuals affected by the interpretation. Further, Kant’s notion of treating humanity, whether in oneself or in another, always as an end and never merely as a means to an end, reinforces the duty to interpret accurately. This ensures that individuals are not misled or harmed through misinterpretation, thus respecting their autonomy and dignity.

\quad Therefore, from a Kantian Deontological perspective, proper interpretation is not merely a professional responsibility but a moral obligation. This statement aligns with Kant’s emphasis on actions that can be universally willed and that inherently respect the autonomy and dignity of others involved. Misinterpretation, by contrast, would undermine trust, dignity, and rational decision-making, thereby violating Kantian moral laws.

\section*{Question 5}
(Free Points) What was the most informative/interesting unit in this course?  The least?

\quad The most interesting unit for me was focused on statistical metrics of fairness, including Statistical Parity (SP) and Disparate Impact (DI). This was particularly engaging due to its relevance in real-world applications and my previous lack of knowledge on the subject. While I found the deep dive into COMPAS also enjoyable and fascinating, the lecture dedicated class-wide discussion felt somewhat repetitive, with the same points being reiterated without adding substantial new insights; I also have concerns about the grading of opinions in such discussions. This aspect of the course could potentially influence the objectivity and fairness of grading, especially in discussions on sensitive topics like fairness and bias.

\quad The least interesting unit for me was on differential privacy. Despite the clear importance of protecting privacy in data analysis, the presentation and explanation in class were somewhat underwhelming. I felt that more detailed examples or engaging visuals, similar to the exemplary bottle analogy used for SVMs, could have made this topic more accessible and intriguing for all students. Such enhancements to the lecture would've likely helped clarify the concepts covered in E-DP and enhance understanding, making the learning experience more effective and enjoyable.

\end{multicols}